name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    name: Build Executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile openscad_export/export.py --name openscad-batch-export
          pyinstaller --onefile openscad_export/gui.py --name openscad-batch-export-gui

      - name: Archive Executables
        if: always()
        run: |
          mkdir dist
          mv dist/* ./dist/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries-${{ matrix.os }}
          path: ./dist/*

  release:
    name: Release Executables
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries-${{ matrix.os }}
          path: ./dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: |
            ## Changes
            See the changelog for details.

            ## Downloads
            Find the standalone executables below for each platform.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openscad-batch-export
          asset_name: openscad-batch-export-${{ matrix.os }}.zip
          asset_content_type: application/zip
# end